[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
grid = { path = "../grid" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.9.0"
base64 = "0.22.1"
uuid = { version = "1.15.1", features = ["v4"] }
